### ISSUE TITLE
Add support for & (and other illegal characters) in password

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/zimbra-addon#1] opened 2017-02-22 16:00 UTC
It seems that if you have a & in the password in the xml file, then the addon fails to login to the interface via the auth ticket.  Please add support for illegal characters (<, &, >, ", ') in the XML configuration file.

**Comment by tonyandrewmeyer** [comment] 2017-02-22 20:01
We have always treated these as bugs in the past.

**Comment by alexkiro** [comment] 2017-02-23 10:02
> We have always treated these as bugs in the past.

TBH, I don't know what we can do here:

 - If a character is illegal then the user needs to escape it right? So we should just update our documentation on that, and close this ticket. 
 - Maybe zimbra allows different kind of configuration file (I doubt it) that are more flexible, but that would be a feature not a bug

@claudiapetre what do you think?

**Comment by claudiapetre** [comment] 2017-02-23 10:06
Each usage of <, &, >, ", ' inside admin's password should be encoded as follows:
`&lt; (<), &amp; (&), &gt; (>), &quot; ("), and &apos; (')`. 
I updated documentation and added support into our addon to convert the characters back.

**Comment by alexkiro** [comment] 2017-02-23 10:07
> I updated documentation and added support into our addon to convert the characters back.

Ahh, ok I got so we did not have support for this. That would be a bug indeed :+1:

**Comment by lorentina** [comment] 2017-02-27 08:33
Verified.

**Comment by tonyandrewmeyer** [comment] 2017-03-02 09:49
What commit made this change? The [changelog](https://github.com/SpamExperts/zimbra-addon/commits/master) doesn't show any changes since September last year, and there's nothing linked here.

Also - where is the documentation that was updated? Shouldn't that be here also?

**Comment by alexkiro** [comment] 2017-03-02 10:45
> I updated documentation and added support into our addon to convert the characters back.

@claudiapetre can you please check @tonyandrewmeyer question? It does seem like nothing was changed here indeed?

**Comment by donici** [comment] 2017-03-02 13:06
@lorentina, please re-test this.

**Comment by lorentina** [comment] 2017-03-02 15:00
Re-tested.

**Closed as completed by lorentina** 2017-03-02 15:00 UTC
Labels: bug, priority-normal, testing
